//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JtExpressCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Description {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Description() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JtExpressCore.Description", typeof(Description).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eccompanyid Not null.
        /// </summary>
        internal static string B001 {
            get {
                return ResourceManager.GetString("B001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customerid Not null.
        /// </summary>
        internal static string B002 {
            get {
                return ResourceManager.GetString("B002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txlogisticid Not null.
        /// </summary>
        internal static string B003 {
            get {
                return ResourceManager.GetString("B003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ordertype Not null.
        /// </summary>
        internal static string B004 {
            get {
                return ResourceManager.GetString("B004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to servicetype Not Null.
        /// </summary>
        internal static string B005 {
            get {
                return ResourceManager.GetString("B005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name sender&gt;name Not Null.
        /// </summary>
        internal static string B006 {
            get {
                return ResourceManager.GetString("B006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender e-mail sender&gt;mailbox Not Null.
        /// </summary>
        internal static string B007 {
            get {
                return ResourceManager.GetString("B007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send phone sender&gt;mobile Not Null.
        /// </summary>
        internal static string B008 {
            get {
                return ResourceManager.GetString("B008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender province sender&gt;prov Not Null.
        /// </summary>
        internal static string B009 {
            get {
                return ResourceManager.GetString("B009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate, the current status is: waiting for confirmation.
        /// </summary>
        internal static string B01 {
            get {
                return ResourceManager.GetString("B01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender district sender&gt;city Not Null.
        /// </summary>
        internal static string B010 {
            get {
                return ResourceManager.GetString("B010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender area sender&gt;area Not Null.
        /// </summary>
        internal static string B011 {
            get {
                return ResourceManager.GetString("B011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender address sender&gt;address Not Null.
        /// </summary>
        internal static string B012 {
            get {
                return ResourceManager.GetString("B012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver name receiver&gt;name Not Null.
        /// </summary>
        internal static string B013 {
            get {
                return ResourceManager.GetString("B013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Phone receiver&gt;mobile Not Null.
        /// </summary>
        internal static string B014 {
            get {
                return ResourceManager.GetString("B014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver province receiver&gt;prov Not Null.
        /// </summary>
        internal static string B015 {
            get {
                return ResourceManager.GetString("B015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver District receiver&gt;city Not Null.
        /// </summary>
        internal static string B016 {
            get {
                return ResourceManager.GetString("B016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Area receiver&gt;area Not Null.
        /// </summary>
        internal static string B017 {
            get {
                return ResourceManager.GetString("B017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Address receiver&gt;address Not Null.
        /// </summary>
        internal static string B018 {
            get {
                return ResourceManager.GetString("B018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created order time createordertime Not Null.
        /// </summary>
        internal static string B019 {
            get {
                return ResourceManager.GetString("B019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate, the current status is: order.
        /// </summary>
        internal static string B02 {
            get {
                return ResourceManager.GetString("B02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send start time sendstarttime Not Null.
        /// </summary>
        internal static string B020 {
            get {
                return ResourceManager.GetString("B020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send end time sendendtime Not Null.
        /// </summary>
        internal static string B021 {
            get {
                return ResourceManager.GetString("B021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method paytype Not Null.
        /// </summary>
        internal static string B022 {
            get {
                return ResourceManager.GetString("B022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total quantity totalquantity Not Null.
        /// </summary>
        internal static string B023 {
            get {
                return ResourceManager.GetString("B023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COD amount itemsvalue Not Null.
        /// </summary>
        internal static string B024 {
            get {
                return ResourceManager.GetString("B024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Item names items&gt;itemname Not Null.
        /// </summary>
        internal static string B025 {
            get {
                return ResourceManager.GetString("B025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Iteam name items&gt;englishName Not Null.
        /// </summary>
        internal static string B026 {
            get {
                return ResourceManager.GetString("B026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item number items&gt;number Not Null.
        /// </summary>
        internal static string B027 {
            get {
                return ResourceManager.GetString("B027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared value（IDR）items&gt;itemvalue Not Null.
        /// </summary>
        internal static string B028 {
            get {
                return ResourceManager.GetString("B028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL items&gt;itemurl Not Null.
        /// </summary>
        internal static string B029 {
            get {
                return ResourceManager.GetString("B029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate, the current status is: no order.
        /// </summary>
        internal static string B03 {
            get {
                return ResourceManager.GetString("B03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender area sender&gt; area Not Exists.
        /// </summary>
        internal static string B030 {
            get {
                return ResourceManager.GetString("B030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver area sender&gt;area Not Exists.
        /// </summary>
        internal static string B031 {
            get {
                return ResourceManager.GetString("B031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực người nhận đang trong vùng dịch.
        /// </summary>
        internal static string B031_STOP {
            get {
                return ResourceManager.GetString("B031-STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items Errros.
        /// </summary>
        internal static string B035 {
            get {
                return ResourceManager.GetString("B035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver email receiver&gt;postcode Errors.
        /// </summary>
        internal static string B036 {
            get {
                return ResourceManager.GetString("B036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customerid not null.
        /// </summary>
        internal static string B038 {
            get {
                return ResourceManager.GetString("B038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not operate, the current state is: successful.
        /// </summary>
        internal static string B04 {
            get {
                return ResourceManager.GetString("B04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customerid don’t have set up part sign.
        /// </summary>
        internal static string B041 {
            get {
                return ResourceManager.GetString("B041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customerid is wrong .
        /// </summary>
        internal static string B042 {
            get {
                return ResourceManager.GetString("B042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not operate, the current state is: failure to collect.
        /// </summary>
        internal static string B05 {
            get {
                return ResourceManager.GetString("B05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate, the current status is: successful receipt.
        /// </summary>
        internal static string B06 {
            get {
                return ResourceManager.GetString("B06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate, the current status is: sign failure.
        /// </summary>
        internal static string B07 {
            get {
                return ResourceManager.GetString("B07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate, the current status is: the order has been canceled.
        /// </summary>
        internal static string B08 {
            get {
                return ResourceManager.GetString("B08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate, the waybill number is empty.
        /// </summary>
        internal static string B09 {
            get {
                return ResourceManager.GetString("B09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate, the signing information is empty (including the waybill number, signing name, signing time can not be empty).
        /// </summary>
        internal static string B10 {
            get {
                return ResourceManager.GetString("B10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal logistics order number.
        /// </summary>
        internal static string B99 {
            get {
                return ResourceManager.GetString("B99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON format not correct.
        /// </summary>
        internal static string S01 {
            get {
                return ResourceManager.GetString("S01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key-parase not correct.
        /// </summary>
        internal static string S02 {
            get {
                return ResourceManager.GetString("S02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID not correct.
        /// </summary>
        internal static string S03 {
            get {
                return ResourceManager.GetString("S03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal notification type.
        /// </summary>
        internal static string S04 {
            get {
                return ResourceManager.GetString("S04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal notification content.
        /// </summary>
        internal static string S05 {
            get {
                return ResourceManager.GetString("S05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out.
        /// </summary>
        internal static string S06 {
            get {
                return ResourceManager.GetString("S06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is abnormal, please try again.
        /// </summary>
        internal static string S07 {
            get {
                return ResourceManager.GetString("S07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegale-commerce platform.
        /// </summary>
        internal static string S08 {
            get {
                return ResourceManager.GetString("S08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task data back.
        /// </summary>
        internal static string S09 {
            get {
                return ResourceManager.GetString("S09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate order number.
        /// </summary>
        internal static string S10 {
            get {
                return ResourceManager.GetString("S10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate waybill number.
        /// </summary>
        internal static string S11 {
            get {
                return ResourceManager.GetString("S11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status is GOT and cannot cancel order.
        /// </summary>
        internal static string S12 {
            get {
                return ResourceManager.GetString("S12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Update is missing &quot;customerid&quot;.
        /// </summary>
        internal static string S15 {
            get {
                return ResourceManager.GetString("S15", resourceCulture);
            }
        }
    }
}
