//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JtExpressCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpecificOccurrence {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecificOccurrence() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JtExpressCore.SpecificOccurrence", typeof(SpecificOccurrence).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON format not correct.
        /// </summary>
        internal static string S01 {
            get {
                return ResourceManager.GetString("S01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key-parase not correct.
        /// </summary>
        internal static string S02 {
            get {
                return ResourceManager.GetString("S02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID not correct.
        /// </summary>
        internal static string S03 {
            get {
                return ResourceManager.GetString("S03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal notification type.
        /// </summary>
        internal static string S04 {
            get {
                return ResourceManager.GetString("S04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal notification content.
        /// </summary>
        internal static string S05 {
            get {
                return ResourceManager.GetString("S05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out.
        /// </summary>
        internal static string S06 {
            get {
                return ResourceManager.GetString("S06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is abnormal, please try again.
        /// </summary>
        internal static string S07 {
            get {
                return ResourceManager.GetString("S07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegale-commerce platform.
        /// </summary>
        internal static string S08 {
            get {
                return ResourceManager.GetString("S08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task data back.
        /// </summary>
        internal static string S09 {
            get {
                return ResourceManager.GetString("S09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate order number.
        /// </summary>
        internal static string S10 {
            get {
                return ResourceManager.GetString("S10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate waybill number.
        /// </summary>
        internal static string S11 {
            get {
                return ResourceManager.GetString("S11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status is GOT and cannot cancel order.
        /// </summary>
        internal static string S12 {
            get {
                return ResourceManager.GetString("S12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Update is missing &quot;customerid&quot;.
        /// </summary>
        internal static string S15 {
            get {
                return ResourceManager.GetString("S15", resourceCulture);
            }
        }
    }
}
